#!/bin/bash
# =============================================================================
# DevStack + Manila Weka Driver Bootstrap Script
# Generated by Terraform — do not edit directly on the instance.
#
# This script runs as root via cloud-init on first boot.
# It performs all steps to stand up a complete DevStack environment with
# the Manila Weka driver wired to the Weka cluster.
#
# Template variables (substituted by Terraform at apply time):
#   weka_backend            = ${weka_backend}
#   weka_nfs_server         = ${weka_nfs_server}
#   weka_password_secret_id = ${weka_password_secret_id}
#   lambda_status_name      = ${lambda_status_name}
#   aws_region              = ${aws_region}
#   devstack_branch         = ${devstack_branch}
#   driver_branch           = ${driver_branch}
#   admin_password          = (sensitive — not echoed)
#
# Runtime variables (fetched/computed at instance boot time):
#   HOST_IP      — private IP from EC2 metadata
#   WEKA_PASSWORD — fetched from AWS Secrets Manager
# =============================================================================

set -euxo pipefail

LOG=/var/log/devstack-bootstrap.log
exec > >(tee -a "$LOG") 2>&1

echo "=== DevStack bootstrap started at $(date) ==="
echo "=== Instance: $(hostname) ==="

# ─── Terraform-substituted configuration ──────────────────────────────────────
WEKA_BACKEND="${weka_backend}"
WEKA_NFS_SERVER="${weka_nfs_server}"
WEKA_SECRET_ID="${weka_password_secret_id}"
LAMBDA_STATUS_NAME="${lambda_status_name}"
AWS_REGION="${aws_region}"
DEVSTACK_BRANCH="${devstack_branch}"
DRIVER_BRANCH="${driver_branch}"
ADMIN_PASSWORD="${admin_password}"

# Persist Weka CLI environment for all SSH sessions — used in demo guides.
# WEKA_PASSWORD is added after it is fetched from Secrets Manager (Step 4).
echo "WEKA_HOST=$${WEKA_BACKEND}" >> /etc/environment
echo "WEKA_USERNAME=admin" >> /etc/environment
echo "WEKA_ORG=Root" >> /etc/environment

# ─── KERNEL PHASE: Ensure kernel 5.15 for WekaFS compatibility ────────────────
# Ubuntu 22.04.4+ ships with the HWE kernel (6.8) which breaks the WekaFS
# kernel module. Phase 1 installs the GA (5.15) kernel and reboots.
# Phase 2 runs this script again via a systemd service after the reboot.

PHASE_SENTINEL=/root/.bootstrap-kernel-ready

if [ ! -f "$PHASE_SENTINEL" ]; then
  echo "=== KERNEL PHASE 1: Installing 5.15 GA kernel for WekaFS compatibility ==="

  export DEBIAN_FRONTEND=noninteractive
  apt-get update -q

  # Install the Ubuntu 22.04 LTS GA kernel for AWS (kernel 5.15)
  if apt-get install -y linux-aws-lts-22.04 linux-headers-aws-lts-22.04 2>/dev/null; then
    echo "Installed linux-aws-lts-22.04 (5.15 kernel)"
  else
    echo "linux-aws-lts-22.04 not found — searching for 5.15 AWS kernel packages..."
    KERN_PKG=$(apt-cache search 'linux-image-5\.15.*-aws$' 2>/dev/null | awk '{print $1}' | sort -V | tail -1)
    HDR_PKG=$(apt-cache search  'linux-headers-5\.15.*-aws$' 2>/dev/null | awk '{print $1}' | sort -V | tail -1)
    if [ -n "$${KERN_PKG}" ]; then
      apt-get install -y "$${KERN_PKG}" "$${HDR_PKG}" || true
    else
      echo "WARNING: No 5.15 AWS kernel found — WekaFS will not work on this host."
    fi
  fi

  # Hold HWE packages so apt upgrade cannot pull 6.8 back in
  apt-mark hold linux-aws linux-image-aws linux-headers-aws 2>/dev/null || true

  # Identify the installed 5.15 kernel version string for GRUB
  KERN_5_15=$(dpkg -l 'linux-image-5.15*-aws' 2>/dev/null \
    | awk '/^ii/{print $2}' | sed 's/linux-image-//' | sort -V | tail -1)

  if [ -n "$${KERN_5_15}" ]; then
    echo "Setting GRUB default to: $${KERN_5_15}"
    sed -i "s|^GRUB_DEFAULT=.*|GRUB_DEFAULT=\"Advanced options for Ubuntu>Ubuntu, with Linux $${KERN_5_15}\"|" \
      /etc/default/grub
    update-grub
  else
    echo "WARNING: Could not identify 5.15 kernel version — GRUB not updated."
  fi

  # Register a systemd service to resume this script after the reboot
  cat > /etc/systemd/system/devstack-bootstrap-continue.service << 'SVCEOF'
[Unit]
Description=DevStack Bootstrap Phase 2 (post-kernel-reboot)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/root/bootstrap.sh
StandardOutput=append:/var/log/devstack-bootstrap.log
StandardError=append:/var/log/devstack-bootstrap.log
TimeoutStartSec=7200

[Install]
WantedBy=multi-user.target
SVCEOF

  systemctl enable devstack-bootstrap-continue.service

  # Write sentinel before reboot so phase 2 skips this block
  touch "$PHASE_SENTINEL"

  echo "=== KERNEL PHASE 1 complete — rebooting to kernel 5.15 in 3 seconds ==="
  sleep 3
  reboot
  exit 0
fi

echo "=== KERNEL PHASE 2: Resumed after reboot — running kernel: $(uname -r) ==="

# ─── STEP 1: System preparation ───────────────────────────────────────────────
echo "=== STEP 1: System preparation ==="

export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get upgrade -y -q
apt-get install -y -q \
  git \
  python3-pip \
  curl \
  wget \
  jq \
  unzip \
  nfs-common \
  crudini \
  screen \
  net-tools \
  bridge-utils \
  iptables \
  dnsmasq-base \
  libssl-dev \
  libffi-dev \
  python3-dev \
  build-essential \
  iputils-ping \
  traceroute \
  tcpdump \
  vim \
  tmux

# Install AWS CLI v2 (use upstream binary for consistent v2 behaviour)
if ! command -v aws &>/dev/null; then
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    -o /tmp/awscliv2.zip
  unzip -q /tmp/awscliv2.zip -d /tmp/
  /tmp/aws/install
  rm -rf /tmp/aws /tmp/awscliv2.zip
fi

# Create the stack user that DevStack requires
if ! id stack &>/dev/null; then
  useradd -s /bin/bash -d /opt/stack -m stack
fi
chmod +x /opt/stack
echo "stack ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/stack
chmod 440 /etc/sudoers.d/stack

echo "=== STEP 1 complete ==="

# ─── STEP 2: Get the private IP of this instance ──────────────────────────────
echo "=== STEP 2: Detect instance IP ==="

TOKEN=$(curl -sf -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" || echo "")

if [ -n "$${TOKEN}" ]; then
  HOST_IP=$(curl -sf -H "X-aws-ec2-metadata-token: $${TOKEN}" \
    http://169.254.169.254/latest/meta-data/local-ipv4)
else
  HOST_IP=$(curl -sf http://169.254.169.254/latest/meta-data/local-ipv4)
fi

echo "Host private IP: $${HOST_IP}"
echo "=== STEP 2 complete ==="

# ─── STEP 3: Wait for Weka cluster to be ready (poll Lambda status) ───────────
echo "=== STEP 3: Waiting for Weka cluster to become ready ==="

MAX_RETRIES=60   # 60 × 30s = 30 minutes
RETRY=0
CLUSTER_READY=false

while [ $${RETRY} -lt $${MAX_RETRIES} ]; do
  RETRY=$((RETRY + 1))
  echo "--- Cluster readiness check $${RETRY}/$${MAX_RETRIES} ---"

  # Poll via the Weka status Lambda function
  LAMBDA_OUT=$(aws lambda invoke \
    --function-name "$${LAMBDA_STATUS_NAME}" \
    --payload '{"type": "progress"}' \
    --region "$${AWS_REGION}" \
    --cli-binary-format raw-in-base64-out \
    /tmp/weka_status.json 2>/dev/null && cat /tmp/weka_status.json || echo "{}")

  echo "Lambda response: $${LAMBDA_OUT}"

  # Check for "clusterized": true in the response (not just the key name)
  if echo "$${LAMBDA_OUT}" | grep -q '"clusterized":true'; then
    echo "Weka cluster is clusterized!"
    CLUSTER_READY=true
    break
  fi

  if [ $${RETRY} -lt $${MAX_RETRIES} ]; then
    echo "Cluster not ready yet — waiting 30 seconds..."
    sleep 30
  fi
done

if [ "$${CLUSTER_READY}" = "false" ]; then
  echo "WARNING: Weka cluster did not report ready after $${MAX_RETRIES} retries."
  echo "Continuing anyway — the Weka agent install may retry internally."
fi

echo "=== STEP 3 complete ==="

# ─── STEP 4: Fetch Weka admin credentials from AWS Secrets Manager ────────────
echo "=== STEP 4: Fetching Weka admin password from Secrets Manager ==="

RETRY=0
WEKA_PASSWORD=""
while [ $${RETRY} -lt 20 ] && [ -z "$${WEKA_PASSWORD}" ]; do
  RETRY=$((RETRY + 1))
  echo "--- Secrets Manager attempt $${RETRY}/20 ---"

  SECRET_VALUE=$(aws secretsmanager get-secret-value \
    --secret-id "$${WEKA_SECRET_ID}" \
    --region "$${AWS_REGION}" \
    --query 'SecretString' \
    --output text 2>/dev/null || echo "")

  if [ -n "$${SECRET_VALUE}" ]; then
    # Try JSON format first (e.g. {"password":"..."})
    WEKA_PASSWORD=$(echo "$${SECRET_VALUE}" | jq -r '.password // empty' 2>/dev/null || true)
    # Fall back to plain string if not JSON
    if [ -z "$${WEKA_PASSWORD}" ]; then
      WEKA_PASSWORD="$${SECRET_VALUE}"
    fi
  fi

  if [ -z "$${WEKA_PASSWORD}" ]; then
    echo "Password not yet available — waiting 30 seconds..."
    sleep 30
  fi
done

if [ -z "$${WEKA_PASSWORD}" ]; then
  echo "ERROR: Could not fetch Weka password from Secrets Manager after retries."
  exit 1
fi

echo "Weka password fetched successfully."
echo "WEKA_PASSWORD=$${WEKA_PASSWORD}" >> /etc/environment
echo "=== STEP 4 complete ==="

# ─── STEP 4b: Delete default Weka filesystem to free up cluster capacity ───────
echo "=== STEP 4b: Removing default Weka filesystem ==="
# Weka's Terraform module creates a 'default' filesystem that consumes ALL
# cluster capacity. Manila cannot create share filesystems until it is removed.

WEKA_API_BASE="https://$${WEKA_BACKEND}:14000/api/v2"

# Authenticate and obtain a token
AUTH_RESPONSE=$(curl -sk -X POST "$${WEKA_API_BASE}/login" \
  -H "Content-Type: application/json" \
  -d "{\"username\":\"admin\",\"password\":\"$${WEKA_PASSWORD}\"}" 2>/dev/null || echo "{}")
WEKA_TOKEN=$(echo "$${AUTH_RESPONSE}" | jq -r '.data.access_token // empty' 2>/dev/null || true)

if [ -z "$${WEKA_TOKEN}" ]; then
  echo "WARNING: Could not authenticate to Weka API — skipping default filesystem deletion."
  echo "         Manila will fail to create shares if the default filesystem exists."
else
  # Find the UID of the 'default' filesystem
  FS_LIST=$(curl -sk -H "Authorization: Bearer $${WEKA_TOKEN}" \
    "$${WEKA_API_BASE}/fileSystems" 2>/dev/null || echo "{}")
  DEFAULT_FS_UID=$(echo "$${FS_LIST}" | jq -r '.data[] | select(.name=="default") | .uid' 2>/dev/null || true)

  if [ -z "$${DEFAULT_FS_UID}" ]; then
    echo "No 'default' filesystem found — nothing to delete."
  else
    echo "Deleting 'default' filesystem (uid=$${DEFAULT_FS_UID})..."
    DEL_RESP=$(curl -sk -X DELETE \
      -H "Authorization: Bearer $${WEKA_TOKEN}" \
      -H "Content-Type: application/json" \
      -d '{"purge_from_obs": false}' \
      "$${WEKA_API_BASE}/fileSystems/$${DEFAULT_FS_UID}" 2>/dev/null || echo "{}")
    echo "Delete response: $${DEL_RESP}"
    echo "Default filesystem deleted — full cluster capacity now available for Manila."
  fi
fi

echo "=== STEP 4b complete ==="

# ─── STEP 5: Install Weka agent (POSIX client) ────────────────────────────────
echo "=== STEP 5: Installing Weka POSIX client agent ==="

# Wait for the Weka API to accept connections (poll install endpoint)
RETRY=0
WEKA_API_READY=false
while [ $${RETRY} -lt 40 ]; do
  RETRY=$((RETRY + 1))
  echo "--- Weka API readiness check $${RETRY}/40 ---"

  HTTP_CODE=$(curl -sk -o /dev/null -w "%%{http_code}" \
    "https://$${WEKA_BACKEND}:14000/dist/v1/install" 2>/dev/null || echo "000")

  echo "HTTP status from Weka install endpoint: $${HTTP_CODE}"

  if [ "$${HTTP_CODE}" = "200" ] || [ "$${HTTP_CODE}" = "302" ]; then
    WEKA_API_READY=true
    break
  fi

  echo "Weka API not ready (HTTP $${HTTP_CODE}) — waiting 30 seconds..."
  sleep 30
done

if [ "$${WEKA_API_READY}" = "true" ]; then
  echo "Downloading and installing Weka agent..."
  curl -sk "https://$${WEKA_BACKEND}:14000/dist/v1/install" | bash || {
    echo "WARNING: Weka agent install returned non-zero. Checking if agent is present..."
    which weka || echo "weka binary not found after install attempt"
  }

  # Download and compile the Weka version — this builds the wekafsio kernel module
  # against the running kernel. Must be done before modprobe wekafsio.
  echo "Downloading Weka version ${weka_version}..."
  if weka version get "${weka_version}" 2>&1; then
    echo "Preparing Weka version ${weka_version} (compiling kernel module)..."
    weka version prepare "${weka_version}" 2>&1 || \
      echo "WARNING: weka version prepare returned non-zero — module may not load."
  else
    echo "WARNING: weka version get failed — wekafsio module will not be available."
  fi
else
  echo "WARNING: Weka API did not become ready for agent install. Continuing..."
  echo "The wekafs module may not be available for Manila. Check /var/log/devstack-bootstrap.log"
fi

# Ensure WekaFS kernel module is loaded
# The Weka client installs the module as 'wekafsio' (with 'wekafsgw' as a dependency)
depmod -a
if modprobe wekafsio 2>/dev/null; then
  echo "wekafs kernel module loaded successfully."
  echo "wekafsio" > /etc/modules-load.d/wekafs.conf
else
  echo "WARNING: Could not load wekafsio module. Manila WekaFS POSIX access will not work."
  echo "NFS protocol mode may still function if configured."
fi

# Create the default WekaFS mount base directory
mkdir -p /mnt/weka
chmod 777 /mnt/weka

echo "=== STEP 5 complete ==="

# ─── STEP 6: Clone DevStack ────────────────────────────────────────────────────
echo "=== STEP 6: Cloning DevStack ($${DEVSTACK_BRANCH}) ==="

sudo -u stack bash -c "
  set -euxo pipefail
  if [ ! -d /opt/stack/devstack/.git ]; then
    git clone https://opendev.org/openstack/devstack /opt/stack/devstack
  fi
  cd /opt/stack/devstack
  git checkout '$${DEVSTACK_BRANCH}'
  git pull --ff-only || true
"

echo "=== STEP 6 complete ==="

# ─── STEP 7: Clone Manila Weka driver ─────────────────────────────────────────
echo "=== STEP 7: Cloning Manila Weka driver (branch: $${DRIVER_BRANCH}) ==="

sudo -u stack bash -c "
  set -euxo pipefail
  if [ ! -d /opt/stack/manila-weka-driver/.git ]; then
    git clone https://github.com/mbookham7/manila-weka-driver \
      /opt/stack/manila-weka-driver
  fi
  cd /opt/stack/manila-weka-driver
  git checkout '$${DRIVER_BRANCH}'
  git pull --ff-only || true
"

echo "=== STEP 7 complete ==="

# ─── STEP 8: Write local.conf ──────────────────────────────────────────────────
echo "=== STEP 8: Writing DevStack local.conf ==="

# NOTE: The WEKA_PASSWORD variable is set above from Secrets Manager.
# It is written directly into local.conf here so DevStack can use it
# during the stack.sh configure phase. The file permissions (stack:stack)
# limit exposure to the instance itself.

cat > /opt/stack/devstack/local.conf << LOCALCONF
[[local|localrc]]
# ── Credentials ──────────────────────────────────────────────────────────────
ADMIN_PASSWORD=$${ADMIN_PASSWORD}
DATABASE_PASSWORD=$${ADMIN_PASSWORD}
RABBIT_PASSWORD=$${ADMIN_PASSWORD}
SERVICE_PASSWORD=$${ADMIN_PASSWORD}

# ── Network ──────────────────────────────────────────────────────────────────
HOST_IP=$${HOST_IP}
# Use 10.0.4.0/24 for Nova floating IPs so they stay within the VPC CIDR
# (10.0.0.0/16). This makes them natively routable via the VPC route table
# and avoids the MASQUERADE-stripping problem with the 172.24.4.0/24 default.
FLOATING_RANGE=10.0.4.0/24
PUBLIC_NETWORK_GATEWAY=10.0.4.1

# ── Paths ────────────────────────────────────────────────────────────────────
DEST=/opt/stack
DATA_DIR=/opt/stack/data

# ── Neutron: force ML2/OVS to avoid OVN (OVN is the new default but
#    incompatible with q-agt which Manila tempest tests require) ───────────────
Q_AGENT=openvswitch
Q_ML2_PLUGIN_MECHANISM_DRIVERS=openvswitch
Q_ML2_PLUGIN_TYPE_DRIVERS=flat,vlan,vxlan,geneve
# AWS EC2 blocks GRE packets — force VXLAN (UDP 4789) which EC2 does support.
# Without this the OVS agent defaults to GRE, port binding fails, and Nova
# cannot boot the manila-service-image VM needed for scenario tests.
Q_TUNNEL_TYPES=vxlan
Q_ML2_TENANT_NETWORK_TYPE=vxlan

# DNS for Nova VMs — required so VMs can resolve hostnames inside the guest.
# Without this dnsmasq has no upstream and guest DNS queries fail, causing
# cloud-init and package installs inside Nova VMs to time out.
DNSMASQ_DNS_SERVERS=8.8.8.8

# ── Services ─────────────────────────────────────────────────────────────────
# Minimal service set for Manila testing (no Cinder, no Swift)
disable_all_services

# Core
enable_service key mysql rabbit

# Nova compute (needed for complete OpenStack env, not strictly required for DHSS=False Manila)
enable_service n-api n-cpu n-cond n-sch n-api-meta placement-api

# Neutron networking (ML2/OVS — q-agt is the OVS agent, not compatible with OVN)
enable_service neutron q-svc q-agt q-dhcp q-l3 q-meta

# Glance images
enable_service g-api

# Manila share service
enable_service manila m-api m-shr m-sch m-dat

# Tempest for integration testing
enable_service tempest

# Horizon dashboard
enable_service horizon

# ── Manila core plugin ───────────────────────────────────────────────────────
# Manila must be enabled before third-party plugins
enable_plugin manila https://opendev.org/openstack/manila $${DEVSTACK_BRANCH}

# Manila Weka driver plugin
# This clones the driver repo and runs devstack/plugin.sh to install the driver
enable_plugin manila-weka-driver https://github.com/mbookham7/manila-weka-driver $${DRIVER_BRANCH}

# Manila tempest plugin for share API tests
enable_plugin manila-tempest-plugin https://opendev.org/openstack/manila-tempest-plugin

# ── Manila backend configuration ──────────────────────────────────────────────
MANILA_ENABLED_BACKENDS=weka
MANILA_SERVICE_IMAGE_ENABLED=False
MANILA_CONFIGURE_DEFAULT_TYPES=True
MANILA_DEFAULT_SHARE_TYPE=weka

# Per-backend options (MANILA_OPTGROUP_<backend>_<option>)
MANILA_OPTGROUP_weka_share_backend_name=weka
MANILA_OPTGROUP_weka_share_driver=manila.share.drivers.weka.driver.WekaShareDriver
MANILA_OPTGROUP_weka_driver_handles_share_servers=False
MANILA_OPTGROUP_weka_snapshot_support=True
MANILA_OPTGROUP_weka_create_share_from_snapshot_support=True
MANILA_OPTGROUP_weka_revert_to_snapshot_support=True

# Weka connection settings (password fetched from Secrets Manager at boot)
MANILA_OPTGROUP_weka_weka_api_server=$${WEKA_BACKEND}
MANILA_OPTGROUP_weka_weka_nfs_server=$${WEKA_NFS_SERVER}
MANILA_OPTGROUP_weka_weka_api_port=14000
MANILA_OPTGROUP_weka_weka_username=admin
MANILA_OPTGROUP_weka_weka_password=$${WEKA_PASSWORD}
MANILA_OPTGROUP_weka_weka_ssl_verify=False
MANILA_OPTGROUP_weka_weka_organization=Root
MANILA_OPTGROUP_weka_weka_filesystem_group=default
MANILA_OPTGROUP_weka_weka_mount_point_base=/mnt/weka
MANILA_OPTGROUP_weka_weka_num_cores=1
MANILA_OPTGROUP_weka_weka_api_timeout=30
MANILA_OPTGROUP_weka_weka_max_api_retries=3

# Allow Manila to open NAS server ports on the local host (required for WekaFS POSIX)
MANILA_ALLOW_NAS_SERVER_PORTS_ON_HOST=True

# ── Logging ───────────────────────────────────────────────────────────────────
LOGFILE=/var/log/stack.sh.log
LOGDAYS=2
VERBOSE=True
LOG_COLOR=False

[[post-config|/etc/manila/manila.conf]]
[DEFAULT]
enabled_share_backends = weka

[weka]
share_backend_name = weka
share_driver = manila.share.drivers.weka.driver.WekaShareDriver
driver_handles_share_servers = False
snapshot_support = True
create_share_from_snapshot_support = True
revert_to_snapshot_support = True
weka_api_server = $${WEKA_BACKEND}
weka_nfs_server = $${WEKA_NFS_SERVER}
weka_api_port = 14000
weka_username = admin
weka_password = $${WEKA_PASSWORD}
weka_ssl_verify = False
weka_organization = Root
weka_filesystem_group = default
weka_mount_point_base = /mnt/weka
weka_num_cores = 1
weka_api_timeout = 30
weka_max_api_retries = 3
LOCALCONF

chown stack:stack /opt/stack/devstack/local.conf
chmod 640 /opt/stack/devstack/local.conf

echo "=== STEP 8 complete ==="

# ─── STEP 9: Run stack.sh (as stack user, in screen session) ──────────────────
echo "=== STEP 9: Starting DevStack stack.sh ==="

# Link the stack.sh log to a standard location
touch /var/log/stack.sh.log
chown stack:stack /var/log/stack.sh.log

# Run stack.sh in a detached screen session
# The script will take 30-45 minutes to complete
sudo -u stack bash -c "
  cd /opt/stack/devstack
  screen -dmS devstack bash -c '
    ./stack.sh > /var/log/stack.sh.log 2>&1
    EXIT_CODE=\$?
    if [ \$EXIT_CODE -eq 0 ]; then
      touch /var/log/devstack-stack-complete
      echo \"stack.sh completed successfully at \$(date)\" >> /var/log/stack.sh.log
    else
      echo \"stack.sh FAILED with exit code \$EXIT_CODE at \$(date)\" >> /var/log/stack.sh.log
    fi
  '
"

echo "stack.sh started in screen session 'devstack'."
echo "Monitor: tail -f /var/log/stack.sh.log"
echo "=== STEP 9 launched (async) ==="

# ─── STEP 10: Wait for stack.sh to complete, then post-configure ──────────────
echo "=== STEP 10: Waiting for stack.sh to complete (up to 60 minutes) ==="

STACK_TIMEOUT=120  # 120 × 30s = 60 minutes
STACK_RETRY=0
STACK_OK=false

while [ $${STACK_RETRY} -lt $${STACK_TIMEOUT} ]; do
  STACK_RETRY=$((STACK_RETRY + 1))

  if [ -f /var/log/devstack-stack-complete ]; then
    echo "stack.sh completed successfully!"
    STACK_OK=true
    break
  fi

  # Check for failure indicators in log
  if grep -q "^Error:" /var/log/stack.sh.log 2>/dev/null; then
    echo "ERROR detected in stack.sh log. Check /var/log/stack.sh.log"
    # Don't exit — try post-config anyway in case Manila started
    break
  fi

  echo "--- Waiting for stack.sh ($${STACK_RETRY}/$${STACK_TIMEOUT}) ---"
  sleep 30
done

if [ "$${STACK_OK}" = "false" ]; then
  echo "WARNING: stack.sh did not complete within timeout or reported errors."
  echo "Attempting post-configuration anyway..."
fi

echo "=== STEP 10 complete ==="

# ─── STEP 11: Post-stack Manila configuration ──────────────────────────────────
echo "=== STEP 11: Post-stack Manila configuration ==="

# Give Manila services a moment to fully start
sleep 10

# Verify Manila services are running
systemctl list-units 'devstack@m-*' --no-pager 2>/dev/null || true

# Re-apply Manila configuration using crudini (belt-and-suspenders)
if [ -f /etc/manila/manila.conf ]; then
  echo "Updating /etc/manila/manila.conf via crudini..."

  # DEFAULT section
  crudini --set /etc/manila/manila.conf DEFAULT enabled_share_backends weka
  crudini --set /etc/manila/manila.conf DEFAULT enabled_share_protocols "NFS,CIFS,WEKAFS"

  # Weka backend section
  crudini --set /etc/manila/manila.conf weka share_backend_name weka
  crudini --set /etc/manila/manila.conf weka share_driver manila.share.drivers.weka.driver.WekaShareDriver
  crudini --set /etc/manila/manila.conf weka driver_handles_share_servers False
  crudini --set /etc/manila/manila.conf weka snapshot_support True
  crudini --set /etc/manila/manila.conf weka create_share_from_snapshot_support True
  crudini --set /etc/manila/manila.conf weka revert_to_snapshot_support True
  crudini --set /etc/manila/manila.conf weka weka_api_server "$${WEKA_BACKEND}"
  crudini --set /etc/manila/manila.conf weka weka_nfs_server "$${WEKA_NFS_SERVER}"
  crudini --set /etc/manila/manila.conf weka weka_api_port 14000
  crudini --set /etc/manila/manila.conf weka weka_username admin
  crudini --set /etc/manila/manila.conf weka weka_password "$${WEKA_PASSWORD}"
  crudini --set /etc/manila/manila.conf weka weka_ssl_verify False
  crudini --set /etc/manila/manila.conf weka weka_organization Root
  crudini --set /etc/manila/manila.conf weka weka_filesystem_group default
  crudini --set /etc/manila/manila.conf weka weka_mount_point_base /mnt/weka
  crudini --set /etc/manila/manila.conf weka weka_num_cores 1

  echo "Restarting Manila services..."
  for svc in devstack@m-shr devstack@m-sch devstack@m-dat devstack@m-api; do
    systemctl restart "$${svc}" 2>/dev/null && echo "Restarted $${svc}" || echo "Could not restart $${svc} (may not exist yet)"
  done

  sleep 5
fi

# Create Manila share type and verify
if [ -f /opt/stack/devstack/openrc ]; then
  echo "Running Manila post-configuration as stack user..."
  sudo -u stack bash -c "
    source /opt/stack/devstack/openrc admin admin

    # Create the Weka share type if it doesn't exist
    if ! manila type-list 2>/dev/null | grep -q 'weka'; then
      manila type-create weka False \
        --extra-specs share_backend_name=weka snapshot_support=True \
          create_share_from_snapshot_support=True revert_to_snapshot_support=True \
        || echo 'WARNING: Could not create Manila share type'
    fi

    echo '--- Manila service list ---'
    manila service-list 2>/dev/null || echo 'Manila not yet responding'

    echo '--- Manila pool list ---'
    manila pool-list --detail 2>/dev/null || echo 'No pools yet'

    echo '--- Manila share types ---'
    manila type-list 2>/dev/null || echo 'No share types yet'
  " || echo "WARNING: Post-config Manila commands failed — stack.sh may still be running"
fi

echo "=== STEP 11 complete ==="

# ─── STEP 12: Configure tempest.conf for Manila DHSS=False testing ───────────
echo "=== STEP 12: Configuring tempest.conf for Manila ==="

TEMPEST_CONF=/opt/stack/tempest/etc/tempest.conf

if [ -f "$${TEMPEST_CONF}" ]; then
  echo "Applying Manila DHSS=False tempest settings..."

  # Enable Manila in tempest
  crudini --set "$${TEMPEST_CONF}" service_available manila True

  # DHSS=False: no share networks, no multitenancy
  crudini --set "$${TEMPEST_CONF}" share multitenancy_enabled False
  crudini --set "$${TEMPEST_CONF}" share run_share_server_tests False
  crudini --set "$${TEMPEST_CONF}" share run_share_network_tests False
  crudini --set "$${TEMPEST_CONF}" share create_networks_when_multitenancy_enabled False

  # Snapshot support
  crudini --set "$${TEMPEST_CONF}" share run_snapshot_tests True
  crudini --set "$${TEMPEST_CONF}" share capability_snapshot_support True

  # Extend/shrink
  crudini --set "$${TEMPEST_CONF}" share run_extend_tests True
  crudini --set "$${TEMPEST_CONF}" share run_shrink_tests True

  # Protocols — driver reports 'WEKAFS NFS'; enable both for API lifecycle tests.
  # NFS is also listed in enable_ro_access_level_for_protocols (WEKAFS access
  # rules are recorded but not NFS-enforced, so RO level is not applicable).
  crudini --set "$${TEMPEST_CONF}" share enable_protocols "nfs,wekafs"
  crudini --set "$${TEMPEST_CONF}" share enable_ro_access_level_for_protocols nfs
  crudini --set "$${TEMPEST_CONF}" share capability_storage_protocol "WEKAFS NFS"

  # Backend
  crudini --set "$${TEMPEST_CONF}" share backend_names weka

  # Scenario tests (mount + read/write inside a Nova VM):
  # - NFS: supported — manila-service-image has NFS client tools
  # - WEKAFS: NOT supported — the Nova VM does not have the Weka client;
  #   WEKAFS coverage is via API lifecycle tests above
  crudini --set "$${TEMPEST_CONF}" share image_with_share_tools manila-service-image-master
  crudini --set "$${TEMPEST_CONF}" share run_basic_ops_tests True

  echo "tempest.conf Manila settings applied."
else
  echo "WARNING: $${TEMPEST_CONF} not found — DevStack may still be running."
  echo "Run 'make reconfigure-manila' after DevStack completes to apply these settings."
fi

echo "=== STEP 12 complete ==="

# ─── STEP 13: Download and register manila-service-image-master in Glance ──────
echo "=== STEP 13: Uploading manila-service-image-master to Glance ==="

# This image is required by the Manila tempest scenario tests (TestShareBasicOpsNFS).
# It is a pre-built VM image that contains NFS client tools so the test can mount
# a share inside a Nova VM and perform real read/write operations.
# Source: https://opendev.org/openstack/manila-image-elements

IMAGE_URL="https://tarballs.opendev.org/openstack/manila-image-elements/images/manila-service-image-master.qcow2"
IMAGE_NAME="manila-service-image-master"
IMAGE_FILE="/tmp/manila-service-image-master.qcow2"

if [ -f /opt/stack/devstack/openrc ]; then
  echo "Downloading $${IMAGE_NAME} (~500 MB, this takes a few minutes)..."
  if wget -q --show-progress -O "$${IMAGE_FILE}" "$${IMAGE_URL}"; then
    echo "Download complete. Uploading to Glance..."
    sudo -u stack bash -c "
      set +u
      source /opt/stack/devstack/openrc admin admin
      set -u
      # Only upload if not already present
      if ! openstack image show '$${IMAGE_NAME}' &>/dev/null; then
        openstack image create \
          --disk-format qcow2 \
          --container-format bare \
          --public \
          --file '$${IMAGE_FILE}' \
          '$${IMAGE_NAME}'
        echo 'Image $${IMAGE_NAME} uploaded to Glance successfully.'
      else
        echo 'Image $${IMAGE_NAME} already exists in Glance — skipping upload.'
      fi
    " || echo "WARNING: Glance image upload failed — scenario tests will be skipped."
    rm -f "$${IMAGE_FILE}"
  else
    echo "WARNING: Failed to download $${IMAGE_NAME} — scenario tests will be skipped."
  fi
else
  echo "WARNING: openrc not found — skipping image upload."
fi

echo "=== STEP 13 complete ==="

# ─── STEP 14: NFS routing — allow Nova VM floating IPs to reach Weka NFS ───────
# Nova VMs get floating IPs in 10.0.4.0/24 (within the VPC CIDR 10.0.0.0/16).
# DevStack adds a MASQUERADE rule that SNATs traffic leaving ens5 to the host IP.
# Insert a RETURN rule before MASQUERADE so that traffic destined for anywhere
# in the VPC (10.0.0.0/16) keeps its floating-IP source address, allowing Weka
# NFS gateway NFS permissions to match correctly.
# The EC2 source/destination check must also be disabled (done via Terraform).
echo "=== STEP 14: Configuring NFS routing for Nova VM floating IPs ==="
iptables -t nat -I POSTROUTING 1 \
  -s 10.0.4.0/24 -d 10.0.0.0/16 -j RETURN
# Persist across reboots
mkdir -p /etc/iptables
iptables-save > /etc/iptables/rules.v4
# Restore on reboot
cat > /etc/network/if-pre-up.d/iptables-restore << 'IPRULES'
#!/bin/sh
iptables-restore < /etc/iptables/rules.v4
IPRULES
chmod +x /etc/network/if-pre-up.d/iptables-restore
echo "=== STEP 14 complete ==="

# ─── STEP 15: Write completion sentinel ────────────────────────────────────────
echo "=== STEP 15: Writing completion sentinel ==="

touch /var/log/devstack-complete
echo "DevStack + Manila Weka driver bootstrap completed at $(date)" \
  | tee /var/log/devstack-bootstrap-complete.log

echo "=== Bootstrap complete! ==="
echo ""
echo "Next steps:"
echo "  1. SSH in: ssh ubuntu@<public_ip> -i <key.pem>"
echo "  2. Check Manila: source /opt/stack/devstack/openrc admin admin && manila service-list"
echo "  3. Run tests: cd /opt/stack/tempest && python -m pytest -k 'manila'"
echo ""
echo "=== DevStack bootstrap finished at $(date) ==="
